{
  pkgs,
  ...
}:
{
  environment.systemPackages = with pkgs; [
    (google-cloud-sdk.withExtraComponents [ google-cloud-sdk.components.gke-gcloud-auth-plugin ])
    awscli2
    azure-cli
    bat
    bluetuith
    brightnessctl
    btop
    cargo
    clang-tools_17
    clippy
    docker
    eza
    file
    gh
    gnupg
    go
    gopls
    gotools
    jq
    k9s
    kubectl
    kubernetes-helm
    linuxHeaders
    man-pages
    man-pages-posix
    nix-output-monitor
    nixd
    nixpkgs-fmt
    nixpkgs-lint
    obsidian
    pass
    pavucontrol
    python3
    rust-analyzer
    rustc
    rustfmt
    slack
    sublime-merge
    terraform
    unzip
    wireguard-tools
    yazi
    yq-go
    zathura
    zed-editor
    zip
    slack
    (callPackage ida-pro {
      runfile = /nix/store/z83flk6c9fm9li3gs13vbamq2szg9rwf-ida-pro_90_x64linux.run;
    })
  ];
}
