name: Update Flake Inputs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23
      - uses: DeterminateSystems/update-flake-lock@da03c0f078bc4b2c37ee4f7e072d34bf8f188bb3 # v29
        with:
          pr-title: Update flake inputs
          pr-labels: dependencies
          token: ${{ secrets.PR_TOKEN }} # Required so CI runs on the PR directly.
          inputs: nixpkgs disko colmena
          pr-assignees: msanft
